[pytest]
# 1. Point to your project's settings
DJANGO_SETTINGS_MODULE = bid_config.settings

# 2. Tell pytest which files are tests
python_files = tests.py test_*.py *_tests.py

# 3. Add professional flags
# --reuse-db: Stops pytest from deleting the test DB every single time (saves 5+ seconds)
addopts = --reuse-db -v