# Generated by Django 6.0.3 on 2026-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_rls_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('view_tenant', 'View Tenant'), ('create_tenant', 'Create Tenant'), ('edit_tenant', 'Edit Tenant'), ('delete_tenant', 'Delete Tenant'), ('view_role', 'View Role'), ('create_role', 'Create Role'), ('edit_role', 'Edit Role'), ('delete_role', 'Delete Role'), ('view_permission', 'View Permission'), ('create_permission', 'Create Permission'), ('edit_permission', 'Edit Permission'), ('delete_permission', 'Delete Permission'), ('view_role_permission', 'View Role Permission'), ('create_role_permission', 'Create Role Permission'), ('edit_role_permission', 'Edit Role Permission'), ('delete_role_permission', 'Delete Role Permission'), ('view_user', 'View User'), ('create_user', 'Create User'), ('edit_user', 'Edit User'), ('delete_user', 'Delete User'), ('view_sale', 'View Sale'), ('create_sale', 'Create Sale'), ('edit_sale', 'Edit Sale'), ('delete_sale', 'Delete Sale'), ('view_inventory', 'View Inventory'), ('create_inventory', 'Create Inventory'), ('edit_inventory', 'Edit Inventory'), ('delete_inventory', 'Delete Inventory'), ('view_activity_log', 'View Activity Log'), ('create_activity_log', 'Create Activity Log'), ('edit_activity_log', 'Edit Activity Log'), ('delete_activity_log', 'Delete Activity Log')], max_length=50),
        ),
    ]
