# Generated by Django 6.0.3 on 2026-03-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_inventory_unit_price_category_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='storefront.inventory'),
            preserve_default=False,
        ),
    ]
