# Generated by Django 6.0.3 on 2026-03-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_remove_sale_product_id_sale_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='max_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
