# Generated by Django 6.0.3 on 2026-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_inventory_max_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(default='TEMP_ID', max_length=255),
            preserve_default=False,
        ),
    ]
