# Generated by Django 6.0.3 on 2026-04-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
