# Generated by Django 6.0.3 on 2026-04-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_sale_iscancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancelReason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
