# Generated by Django 6.0.3 on 2026-04-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_sale_cancelreason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='cancelReason',
            new_name='cancel_reason',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='isCancelled',
            new_name='is_cancelled',
        ),
    ]
